### PR TITLE
Fixed 'something went wrong' toast appearing on tab switch (#1x0k51t)

### LINKED ISSUE #83: When switching between tabs something went wrong appears
## Current behavior

When switching between tabs something went wrong appears.

## Expected behavior

If we go to another tab from the picklist page, 'something went wrong' should not appear and if we move to the picklist page and no picklists are found, 'something went wrong' should be displayed.

## Steps to reproduce the issue

1. Go to the picklist page
2. If no picklists are found 'something went wrong'  appears.
3. Move to the settings page and see that 'something went wrong'  appears again.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #83

### Short Description and Why It's Useful

Fixed toast appearing when switching tabs. The toast was caused by the findPickilist action being called globally, on all routes, stating there are no picklists. Hence, made the action to not be called on the settings route.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/views/Picklists.vue [hunk 1]
```diff
@@ -51,9 +51,11 @@ export default defineComponent({
     })
   },
   updated () {
-    this.store.dispatch('picklist/findPickList').catch(err =>
-      this.store.dispatch('picklist/clearPicklist')
-    )
+    if(this.$route.path != "/tabs/settings") {
```
Comment (ymaheshwari1) [inline src/views/Picklists.vue:54]: This condition will not handle the case when we will have a new route.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/views/Picklists.vue (hunk 1 above)
Comment (k2maan) [reply src/views/Picklists.vue:54]: Sure, sir, will look into it.

File: src/views/Picklists.vue [hunk 2]
```diff
@@ -50,10 +50,10 @@ export default defineComponent({
       picklists: 'picklist/getPicklists'
     })
   },
-  updated () {
-    this.store.dispatch('picklist/findPickList').catch(err =>
-      this.store.dispatch('picklist/clearPicklist')
-    )
+  ionViewDidEnter() {
+      this.store.dispatch('picklist/findPickList').catch(err =>
```
Comment (ymaheshwari1) [inline src/views/Picklists.vue:54]: Fix indentation.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Review by ymaheshwari1 — APPROVED** [review]

**Review by adityasharma7 — APPROVED** [review]
